version: '3'

services:
  db:
    image: postgres:13
    restart: always
    env_file:
      - .env
    volumes:
      - "./postgres:/var/lib/postgresql/data"
    ports:
      - "5432:5432"

  api:
    build: ./
    env_file:
      - .env
    restart: always
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/app
      - /data/static:/app/static
      - /data/media:/app/media
    ports:
      - "8000:8000"
    depends_on:
      - db
    tty: true